#!/bin/bash

name=${1}

in_folder="run"

if [[ ${name} == "-all" ]]; then
  for experiment in $(find ${in_folder} -name="hdgen.*" ! -name "hdgen.*.run"); do
    cd ${in_folder}
    make_target_runscript ${experiment}
    cd -
  done
else
  cd ${in_folder}
  ${in_folder}/make_target_runscript ${name}
  cd -
fi
