RM := rm -rf
.PHONY: clean
clean :
		-$(RM) ./bin/f2py_setup_wrapper.py ./build ./libs/break_loops_driver.so ./libs/mod_check_for_value.so \
		./libs/mod_res_size_init_kernel.so ./libs/break_loops_driver_mod.so ./libs/mod_compute_catchments.so
		-$(RM) ./libs/mod_river_mouth_kernels.so ./libs/cotat_plus_driver_mod.so ./libs/mod_find_mode.so ./libs/mod_topo_io.so \
		./libs/create_connected_lsmask_wrapper.cpython-39-darwin.so ./libs/mod_grid_flow_direction_kernels.so ./libs/fill_sinks_wrapper.cpython-39-darwin.so \
		./libs/fill_sinks_wrapper_low_mem.cpython-39-darwin.so ./libs/upscale_orography_wrapper.cpython-39-darwin.so ./libs/compute_catchments_wrapper.cpython-39-darwin.so \
		./libs/mod_local_minima_finding_kernels.so ./libs/lake_operators_wrapper.cpython-39-darwin.so ./libs/evaluate_basins_wrapper.cpython-39-darwin.so \
		./libs/determine_river_directions_wrapper.cpython-39-darwin.so \
		./libs/create_orography_wrapper.cpython-39-darwin.so
		-$(RM) ./libs/mod_local_minima_finding_kernels.so.dSYM \
		./libs/mod_check_for_value.so.dSYM \
		./libs/mod_res_size_init_kernel.so.dSYM \
		./libs/mod_iterate_paths_map.so.dSYM \
		./libs/mod_topo_io.so.dSYM \
		./libs/mod_grid_flow_direction_kernels.so.dSYM \
		./libs/mod_river_mouth_kernels.so.dSYM \
		./libs/mod_find_mode.so.dSYM \
		./libs/mod_compute_catchments.so.dSYM \
		./libs/cotat_plus_driver_mod.so.dSYM \
    ./libs/break_loops_driver_mod.so.dSYM \
    ./libs/determine_river_directions_wrapper.so.dSYM \
    ./libs/create_orography_wrapper.so.dSYM
		-$(RM) ./libs/mod_iterate_paths_map.so
