RM := rm -rf
.PHONY: clean 
clean : 
		-$(RM) ./bin/f2py_wrapper ./build ./libs/break_loops_driver.so ./libs/mod_check_for_value.so \
		./libs/mod_res_size_init_kernel.so ./libs/break_loops_driver_mod.so ./libs/mod_compute_catchments.so  
		-$(RM) ./libs/mod_river_mouth_kernels.so ./libs/cotat_plus_driver_mod.so ./libs/mod_find_mode.so ./libs/mod_topo_io.so \
		./libs/create_connected_lsmask_wrapper.so ./libs/mod_grid_flow_direction_kernels.so ./libs/fill_sinks_wrapper.so 
		-$(RM) ./libs/mod_iterate_paths_map.so