#!/bin/bash

output_script = ${1}

cat > ${output_script} << EOF
#!/bin/bash
#SBATCH --job-name=????
#SBATCH --partition=compute2,compute
#SBATCH --account=????
#SBATCH --exclusive
#SBATCH --mem-per-cpu=1000
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks=1
#SBATCH --time=02:00:00
#SBATCH --output=upscale_3s_orography.o%j    # File name for standard output
#SBATCH --error=upscale_3s_orography.e%j     # File name for standard error output
EOF
